### ISSUE TITLE
Accessories doesn't sync

### ISSUE THREAD

**Issue by felipehjcosta** [maxileith/homebridge-appletv-enhanced#164] opened 2024-01-07 13:48 UTC
### Analysis

I've noticed that the Apple TV accessory doesn't change to the correct state when I use the Turn On or Turn Off buttons. Also, it doesn't work the other way around either

### Expected Behavior

The Apple TV accessory and buttons should sync properly.

### Steps To Reproduce

https://github.com/maxileith/homebridge-appletv-enhanced/assets/2865924/22211fe3-564c-46fa-a827-2b48d5ae06fa

### Logs

```console
[1/7/2024, 10:47:36 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_on
[1/7/2024, 10:47:50 AM] [Apple TV Enhanced] Platform: Starting device discovery ...
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: finished multicast device discovery
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: Found Apple TV Living Room (3) (EC:A9:07:21:AD:F9 / 192.168.1.230).
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: Apple TV Living Room (3) (EC:A9:07:21:AD:F9) with UUID 87cca5a0-c5dd-4fd6-a927-d3a53f6858aa already exists. Skipping.
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: Finished device discovery.
[1/7/2024, 10:48:00 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: Skipping heartbeat since last command was only 24s before.
[1/7/2024, 10:48:13 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_off
[1/7/2024, 10:48:22 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_off
[1/7/2024, 10:48:29 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_on
[1/7/2024, 10:48:37 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_on
```

### Configuration

```JSON
{
    "mediaTypes": [
        "music",
        "tv",
        "unknown",
        "video"
    ],
    "deviceStates": [],
    "remoteKeysAsSwitch": [
        "turn_off",
        "turn_on"
    ],
    "customInputURIs": [],
    "discover": {
        "unicast": [],
        "blacklist": [],
        "multicast": true
    },
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "forceVenvRecreate": false,
    "logLevel": 4,
    "_bridge": {
        "username": "0E:A9:87:29:EB:F0",
        "port": 55391
    },
    "platform": "AppleTVEnhanced"
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Docker: false
- Homebridge: 4.54.1
- Apple TV Enhanced:
- Node: v20.10.0
- npm: v10.2.3
- Python: 3.9.2
- pip: 20.3.4

**Comment by maxileith** [comment] 2024-01-07 14:01
Duplicate of #155

**Closed by maxileith** 2024-01-07 14:01 UTC
Labels: bug

**Comment by felipehjcosta** [comment] 2024-01-07 14:17
Hey @maxileith it's not the same issue. My interaction in this issue wasn't with the physical remote control.

**Comment by maxileith** [comment] 2024-01-07 14:21
Does the active state of the Apple TV accessory update when using the physical remote?

**Comment by felipehjcosta** [comment] 2024-01-07 14:24
I've created another one: https://github.com/maxileith/homebridge-appletv-enhanced/issues/167

**Comment by maxileith** [comment] 2024-01-07 14:25
Don't mess up the issues. Why not reopen this issue? I am gonna delete #167

**Comment by maxileith** [comment] 2024-01-07 14:27
From #155 it becomes clear that you are using HomePods as your default speakers.

From the README:

> -   If using external speakers like HomePods as the default, the Apple TV is always reported as powered on. This is a known issue of the dependency [pyatv](https://pyatv.dev), see [postlund/pyatv#1667](https://github.com/postlund/pyatv/issues/1667). As a result, the Apple TV device will only be shown as off in HomeKit when powered off via the Apple TV device in HomeKit. After restarting the plugin the device will always be shown as on.

**Comment by felipehjcosta** [comment] 2024-01-07 14:32
That's sad. 😢 

I will follow the original issue on pyatv thanks!
