### ISSUE TITLE
Unable to pair discovered AppleTV devices. 

### ISSUE THREAD

**Issue by rxcid** [maxileith/homebridge-appletv-enhanced#554] opened 2024-08-20 23:47 UTC
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

I have added the AppleTV Enhanced plugin to my Raspberry Pi 4 64bit on Homebridge and configured it in what I thought was correct. After my AppleTV is discovered I get the "[W] Bedroom (C8:69:CD:79:7A:CC): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://x.x.x.x:42166/". (Cleared out IP) When I click the link to enter the pairing code, it opens a new tab but it is a about: blank page and nothing ever loads. The plugin then goes into a loop because I can't pair it. I then have to disable it because I cannot get it to work. 

### Logs

```console
8/20/2024, 7:09:04 PM] [Apple TV Enhanced] [I] Update check: You are using the latest version of AppleTV Enhanced (excluding betas): 1.5.2
[8/20/2024, 7:09:04 PM] [Apple TV Enhanced] [I] Python check: Starting python check.
[8/20/2024, 7:09:04 PM] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[8/20/2024, 7:09:05 PM] [Apple TV Enhanced] [I] Python check: Python 3.11.2 is installed and supported by the plugin.
[8/20/2024, 7:09:05 PM] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[8/20/2024, 7:09:05 PM] [Apple TV Enhanced] [I] Python check: Virtual environment is using the systems default python environment. Continuing ...
[8/20/2024, 7:09:06 PM] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.2
[8/20/2024, 7:09:06 PM] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[8/20/2024, 7:09:06 PM] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[8/20/2024, 7:09:07 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: e4a7bd31-ce4b-11ec-a9b6-0ad630bcd6de structureId: e4a7bd31-ce4b-11ec-a9b6-0ad630bcd6de
[8/20/2024, 7:09:07 PM] [Nest] initing lock (P) "Entryway Lock": deviceId: 00177A00000B9B5B structureId: e4a7bd31-ce4b-11ec-a9b6-0ad630bcd6de
[8/20/2024, 7:09:08 PM] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[8/20/2024, 7:09:08 PM] [Apple TV Enhanced] [I] Python check: Finished
[8/20/2024, 7:09:08 PM] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[8/20/2024, 7:09:15 PM] [Apple TV Enhanced] [I] Platform: Adding Apple TV Bedroom (C8:69:CD:79:7A:CC)
[8/20/2024, 7:09:15 PM] [Apple TV Enhanced] [W] Bedroom (C8:69:CD:79:7A:CC): Credentials are no longer valid. Need to repair ...
[8/20/2024, 7:09:15 PM] [Apple TV Enhanced] [W] Bedroom (C8:69:CD:79:7A:CC): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.13.0.152:42166/
[8/20/2024, 7:09:47 PM] [Apple TV Enhanced] [W] Bedroom (C8:69:CD:79:7A:CC): Pairing request timed out, retrying ...
[8/20/2024, 7:09:47 PM] [Apple TV Enhanced] [W] Bedroom (C8:69:CD:79:7A:CC): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.13.0.152:42166/
[8/20/2024, 7:09:49 PM] [Apple TV Enhanced] [W] Bedroom (C8:69:CD:79:7A:CC): Apple TV Bedroom: Too many attempts. Waiting for 10773 seconds before retrying. The webpage to pair the Apple TV will become available again when the plugin is attempting the next pairing attempt.
[8/20/2024, 7:10:24 PM] [Homebridge UI] Changes to config.json saved.
[8/20/2024, 7:10:25 PM] [Homebridge UI] Homebridge restart request received
[8/20/2024, 7:10:25 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/20/2024, 7:10:25 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/20/2024, 7:10:25 PM] Got SIGTERM, shutting down Homebridge...
[8/20/2024, 7:10:33 PM] [Homebridge UI] Sending SIGKILL to Homebridge
[8/20/2024, 7:10:33 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/20/2024, 7:10:38 PM] [HB Supervisor] Restarting Homebridge...
[8/20/2024, 7:10:38 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/20/2024, 7:10:38 PM] [HB Supervisor] Started Homebridge v1.8.4 with PID: 18208
[8/20/2024, 7:10:39 PM] Loaded config.json with 0 accessories and 4 platforms.
[8/20/2024, 7:10:39 PM] Loaded 3 cached accessories from cachedAccessories.
[8/20/2024, 7:10:39 PM] ---
[8/20/2024, 7:10:39 PM] Disabled plugin: homebridge-appletv-enhanced@1.5.2
[8/20/2024, 7:10:39 PM] ---
[8/20/2024, 7:10:39 PM] Loaded plugin: homebridge-nest@4.6.9
[8/20/2024, 7:10:39 PM] Registering platform 'homebridge-nest.Nest'
[8/20/2024, 7:10:39 PM] ---
[8/20/2024, 7:10:40 PM] Loaded plugin: homebridge-noip@3.0.3
[8/20/2024, 7:10:40 PM] Registering platform 'homebridge-noip.NoIP'
[8/20/2024, 7:10:40 PM] ---
[8/20/2024, 7:10:40 PM] Loading 4 platforms...
[8/20/2024, 7:10:40 PM] [Nest] Initializing Nest platform...
[8/20/2024, 7:10:40 PM] [NoIP] Initializing NoIP platform...
[8/20/2024, 7:10:40 PM] [NoIP] Using Default Refresh Rate of 30 minutes.
[8/20/2024, 7:10:40 PM] Ignoring config for the platform "AppleTVEnhanced" in your config.json as the plugin "homebridge-appletv-enhanced" has been disabled.
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "music",
        "tv",
        "unknown",
        "video"
    ],
    "deviceStates": [
        "idle",
        "loading",
        "paused",
        "playing",
        "seeking",
        "stopped"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "channel_down",
        "channel_up",
        "down",
        "home",
        "home_hold",
        "left",
        "menu",
        "next",
        "pause",
        "play",
        "play_pause",
        "previous",
        "right",
        "select",
        "skip_backward",
        "skip_forward",
        "stop",
        "turn_off",
        "turn_on",
        "top_menu",
        "up",
        "volume_down",
        "volume_up"
    ],
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "updateCheckLevel": "stable",
    "updateCheckTime": 3,
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

NAME="Raspbian GNU/Linux"

### Operating System: Distribution Version

VERSION="12 (bookworm)"

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.4

### Homebridge Config UI Version

v4.56.4

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.5.2

### Node Version

18.19.0

### NPM Version

9.2.0

### Python Version

3.11.2

### PIP Version

pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)

### HDMI Hops

None

### Audio Output

no

### Same Subnet

yes

**Comment by rxcid** [comment] 2024-08-21 03:08
1. I have enabled the “debug logging”
2. I have updated the node version to 20.16.0
3. I have updated the PIP version to 24.2 

I re ran the discovery of the appletv and I still am receiving the about blank page.

**Comment by maxileith** [comment] 2024-08-21 06:51
Duplicate of #290

**Closed** 2024-08-21 06:53 UTC
Labels: support request, bad request
