### ISSUE TITLE
Python release error with Synology

### ISSUE THREAD

**Issue by RSantelises** [maxileith/homebridge-appletv-enhanced#758] opened 2024-11-22 12:37 UTC
### Preconditions

- [X] The issue is not covered by any of the other issue templates

### Issue

I am having an issue with the plugin. I am getting an error after startup:
11/22/2024, 7:16:06 AM] [Apple TV Enhanced] [E] Python check: Python 3.8.15 is installed. However, only Python 3.9 to 3.11 is supported.
[11/22/2024, 7:21:06 AM] [Apple TV Enhanced] [E] Python check: Python 3.8.15 is installed. However, only Python 3.9 to 3.11 is supported.
[11/22/2024, 7:26:06 AM] [Apple TV Enhanced] [E] Python check: Python 3.8.15 is installed. However, only Python 3.9 to 3.11 is supported.

However, I am running 3.10 Python as a Package on my Synology NAS so I am not sure why is finding 3.8.15?

**Comment by maxileith** [comment] 2024-11-22 12:39
Duplicate of #757

**Closed** 2024-11-22 12:50 UTC
