### ISSUE TITLE
One of my Apple TV’s is not discovered during the pairing process

### ISSUE THREAD

**Issue by ahwman** [maxileith/homebridge-appletv-enhanced#18] opened 2023-11-06 05:02 UTC
I have seven Apple TVs, and for some reason, only one of the seven is not discovered during the pairing process.  They are all hardwired and Airplay settings/permissions are set to everyone.  I’ve restarted everything multiple times to no avail.

**Comment by maxileith** [comment] 2023-11-06 07:01
@ahwman Which version are you running?

**Comment by ahwman** [comment] 2023-11-06 12:37
v0.3.1-beta.2

**Comment by maxileith** [comment] 2023-11-06 16:05
So to keep all the informations together ... @ahwman and me were chatting on reddit about this issue. Here is the conversation:

@ahwman 
> Hi there,
> Regarding the issue with one of my ATV’s (latest HD model) not being found, I can’t put my finger on why just this one isn’t being discovered. I have a total of 7 ATV’s and all but this one have been discovered by the plugin. All are hard wired…

@maxileith
> Is this your only Apple TV HD and the others are all 4K?

@ahwman 
> No, I have 2 other HD’s that were discovered and are working fine.

@maxileith 
> Check in the AirPlay settings of your Apple TV if the access is set to everyone or Anyone in the same network

@ahwman 
> AirPlay is set to everyone.

@maxileith 
> Can you send me the output of `/var/lib/homebridge/appletv-enhanced/.vent/bin/atvscript scan`? where `/var/lib/homebridge` is the storage path of your homebridge. It is probably different since you are on Mac. You can see it on the dashboard.

@ahwman 
> I  don’t see a file named atvscript in the following path: /Users/\<username\>/.homebridge/appletv-enhanced/.venv/bin
> [...]
> I’ve honestly scoured my hard drive and just cannot locate this file. How frustrating. Could it possibly be named something different on Mac?

**Comment by maxileith** [comment] 2023-11-06 16:09
@ahwman the atvscript really has to be in the path `/Users/<username>/.homebridge/appletv-enhanced/.venv/bin`. Could you please enable debug mode on your Homebridge, then restart. There will be a log message like `Set atvscript path to "/Users/<username>/.homebridge/appletv-enhanced/.venv/bin".`. This is the location of your atvscript.

**Comment by ahwman** [comment] 2023-11-06 21:43
I enabled logging on Homebridge as you suggested, and found the following line in the log files, which happens to be the missing Apple TV. Any ideas?

E3A1DB34-2984-4976-AA4B-5FB748A94117 is not a MAC-Address. Master Bedroom Apple TV (192.168.1.117) is therefore skipped.[39m

**Comment by maxileith** [comment] 2023-11-07 07:37
Closing since this issue is a duplicate of #20

**Closed** 2023-11-07 07:37 UTC
Labels: duplicate
