### ISSUE TITLE
Accessories doesn't sync on Apple Home app

### ISSUE THREAD

**Issue by felipehjcosta** [maxileith/homebridge-appletv-enhanced#167] opened 2024-01-07 14:21 UTC
### Analysis

I've noticed that the Apple TV accessory doesn't change to the correct state when I use the Turn On or Turn Off buttons. Also, it doesn't work the other way around either

### Expected Behavior

The Apple TV accessory and buttons should sync properly.

### Steps To Reproduce

https://github.com/maxileith/homebridge-appletv-enhanced/assets/2865924/22211fe3-564c-46fa-a827-2b48d5ae06fa

### Logs

```console
[1/7/2024, 10:47:36 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_on
[1/7/2024, 10:47:50 AM] [Apple TV Enhanced] Platform: Starting device discovery ...
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: finished multicast device discovery
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: Found Apple TV Living Room (3) (EC:A9:07:21:AD:F9 / 192.168.1.230).
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: Apple TV Living Room (3) (EC:A9:07:21:AD:F9) with UUID 87cca5a0-c5dd-4fd6-a927-d3a53f6858aa already exists. Skipping.
[1/7/2024, 10:47:57 AM] [Apple TV Enhanced] Platform: Finished device discovery.
[1/7/2024, 10:48:00 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: Skipping heartbeat since last command was only 24s before.
[1/7/2024, 10:48:13 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_off
[1/7/2024, 10:48:22 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_off
[1/7/2024, 10:48:29 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_on
[1/7/2024, 10:48:37 AM] [Apple TV Enhanced] Apple TV Living Room (EC:A9:07:21:AD:F9): Rocket Remote: turn_on
```

### Configuration

```JSON
{
    "mediaTypes": [
        "music",
        "tv",
        "unknown",
        "video"
    ],
    "deviceStates": [],
    "remoteKeysAsSwitch": [
        "turn_off",
        "turn_on"
    ],
    "customInputURIs": [],
    "discover": {
        "unicast": [],
        "blacklist": [],
        "multicast": true
    },
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "forceVenvRecreate": false,
    "logLevel": 4,
    "_bridge": {
        "username": "0E:A9:87:29:EB:F0",
        "port": 55391
    },
    "platform": "AppleTVEnhanced"
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Docker:  false
- Homebridge: 1.7.0
- Homebridge Config UI: 4.54.1
- Storage Path: 
- Apple TV Enhanced: 
- Node: v20.10.0
- npm: v10.2.3
- Python: 3.9.2
- pip: 20.3.4
- HDMI hops:  false
- HomePod as default speaker: true

### Additional Context

Not the same as https://github.com/maxileith/homebridge-appletv-enhanced/issues/155

**Comment by maxileith** [comment] 2024-01-07 14:26
Duplicate of #164

**Closed by maxileith** 2024-01-07 14:26 UTC
Labels: bug
