### ISSUE TITLE
Disable / hide remote in remote app?

### ISSUE THREAD

**Issue by mensa84** [maxileith/homebridge-appletv-enhanced#685] opened 2024-10-17 19:26 UTC
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hello, is it possible to disable or hide the remote in the remote app of the iPhone?
There the original Apple TV is working without problems and I don't want to have the same Apple TV twice as remote in there. Could you please make that adjustable?

**Comment by jsiegenthaler** [comment] 2024-10-18 03:57
I think this user has a good point. 

Technically this is totally possible. Add a config option to not load the remote control service.

**Comment by maxileith** [comment] 2024-10-18 05:24
duplicate of #199, #253, #254

**Closed** 2024-10-18 05:24 UTC
Labels: general question
