### ISSUE TITLE
Solution needed for The directory '/home/homebridge/.cache/pip' or its parent directory is not owned or is not writable by the current user.

### ISSUE THREAD

**Issue by jsiegenthaler** [maxileith/homebridge-appletv-enhanced#289] opened 2024-02-27 17:26 UTC
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

On Homebridge restart, Apple TV Enhanced displays the following in the Homebridge logs:
 
[27/02/2024, 18:17:11] [Apple TV Enhanced] [W] Python check: WARNING: The directory '/home/homebridge/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

There is no clear information on what needs to be done to resolve the issue. Stating "you should use sudo's -H flag." means nothing to the user. There is no information as to what the permissions should be, and how to fix them if they are wrong.

### Logs

```console
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced
[27/02/2024, 18:40:44] [Apple TV Enhanced] [D] Platform: Executed didFinishLaunching callback
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: Starting python check.
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: Python 3.9.2 is installed and supported by the plugin.
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[27/02/2024, 18:40:45] [Apple TV Enhanced] [I] Python check: Venv is using current system python version (3.9.2).
[27/02/2024, 18:40:46] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.0
[27/02/2024, 18:40:46] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[27/02/2024, 18:40:47] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[27/02/2024, 18:40:48] [Apple TV Enhanced] [W] Python check: WARNING: The directory '/home/homebridge/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[27/02/2024, 18:40:48] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[27/02/2024, 18:40:48] [Apple TV Enhanced] [I] Python check: Finished
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] Platform: Setting the storage path of the PyATV instance to /var/lib/homebridge
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] CustomPyATVInstance: Set atvscript path to "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript".
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] CustomPyATVInstance: Set atvremote path to "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvremote".
[27/02/2024, 18:40:48] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] Platform: Starting device discovery ...
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: finished multicast device discovery
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: Found Apple TV Lounge (90:DD:5D:C5:8C:6B / 192.168.0.153).
[27/02/2024, 18:40:55] [Apple TV Enhanced] [I] Platform: Adding Apple TV Lounge (90:DD:5D:C5:8C:6B)
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: Waiting for Apple TV Lounge (90:DD:5D:C5:8C:6B) to boot ...
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Accessory Config: {"name":"Apple TV Enhanced","mediaTypes":["music","tv"],"deviceStateDelay":0,"remoteKeysAsSwitch":["pause","play"],"avadaKedavraAppAmount":15,"disableVolumeControlRemote":false,"setTopBox":false,"discover":{"multicast":true},"forceVenvRecreate":false,"logLevel":4,"deviceSpecificOverrides":[{"overrideMediaTypes":false,"overrideDeviceStates":false,"overrideDeviceStateDelay":false,"deviceStateDelay":0,"overrideRemoteKeysAsSwitch":false,"overrideAvadaKedavraAppAmount":false,"avadaKedavraAppAmount":15,"overrideCustomInputURIs":false,"overrideDisableVolumeControlRemote":false,"disableVolumeControlRemote":false,"overrideSetTopBox":false,"setTopBox":false}],"platform":"AppleTVEnhanced"}
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Loaded credentials: undefined
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Loaded credentials: undefined
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: Finished device discovery.
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Got empty credentials, initiating pairing process.
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Wait for the atvremote process to terminate
[27/02/2024, 18:40:55] [Apple TV Enhanced] [W] Lounge (90:DD:5D:C5:8C:6B): Credentials are no longer valid. Need to repair ...
[27/02/2024, 18:40:55] [Apple TV Enhanced] [W] Lounge (90:DD:5D:C5:8C:6B): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://192.168.0.100:42153/
[27/02/2024, 18:40:57] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): stdout: 2024-02-27 18:40:57 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/support/__init__.py", line 71, in error_handler
    return await func(*args, **kwargs)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 63, in start_pairing
    pairing_data = _get_pairing_data(resp)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 33, in _get_pairing_data
    raise exceptions.AuthenticationError(stringify(tlv))
pyatv.exceptions.AuthenticationError: Error=BackOff, BackOff=9383s, SeqNo=M2
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 196, in pair
    await self._perform_pairing(pairing)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 206, in _perform_pairing
    await pairing.begin()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/companion/pairing.py", line 47, in begin
    await error_handler(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/support/__init__.py", line 77, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: Error=BackOff, BackOff=9383s, SeqNo=M2

[27/02/2024, 18:40:57] [Apple TV Enhanced] [W] Lounge (90:DD:5D:C5:8C:6B): Apple TV Lounge: Too many attempts. Waiting for 9388 seconds before retrying.
[27/02/2024, 18:40:57] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): 9388 seconds remaining.
[27/02/2024, 18:40:58] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): 9387 seconds remaining.

```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "music",
        "tv"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "pause",
        "play"
    ],
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "0E:17:50:E5:71:23",
        "port": 57763
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

 NAME="Raspbian GNU/Linux"

### Operating System: Distribution Version

 VERSION="11 (bullseye)"

### Docker

no

### Docker Image

None

### Homebridge Version

1.7.0

### Homebridge Config UI Version

4.55.1

### Homebridge Storage Path

	/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.2.4

### Node Version

v20.11.1

### NPM Version

10.2.4

### Python Version

3.9.2

### PIP Version

20.3.4

### HDMI Hops

AV Receiver

### Audio Output

no

### Same Subnet

yes

### Additional Context

This is a new installation of Apple TV Enhanced that has not yet been paired to the Apple TV, as pairing does not work yet. A separate Issue will be opened for the pairing problems.

**Comment by maxileith** [comment] 2024-02-27 18:27
The first thing I would check is whether or not the `/home/homebridge/.cache/pip` directory is owned by your homebridge user.

**Comment by maxileith** [comment] 2024-02-29 14:26
Closing since this is not the fault of Apple TV Enhanced but the python installation of the system. Pip errprs are handled by pip itself and the original error message is logged. The error message makes it clear what the issue is.

**Closed by maxileith** 2024-02-29 14:26 UTC
Labels: support request

**Comment by jsiegenthaler** [comment] 2024-02-29 16:27
Hi

I'm by no means a python expert and I have no clue what to do to fix the
error
It only appears with Apple TV Enhanced and thus  link the issue with the
plugin
I think this should go in a Wiki or FAQ entry
