### ISSUE TITLE
How to change or reset timeout for pairing to Apple TV

### ISSUE THREAD

**Issue by rdeutsch3** [maxileith/homebridge-appletv-enhanced#553] opened 2024-08-20 22:22 UTC
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

I've got 3 Apple TVs. Getting the first pairing was no sweat. The second I was able to get downstairs and do in before the next interval of 180s(? I think). But now with the third one the time interval is 10773 seconds. I've tried restarting the plug-in child bridge and it immediately fails the first connection to the TV, it doesn't show me anything on the TV, and then falls back to 10773 seconds.

Is there any way to adjust the retry interval or do something so I'm not trying to remember I've got to go try and pair it 2h59m33s from now?

### Logs

```console
[8/20/2024, 2:47:28 PM] [Apple TV Enhanced] [W] Garage TV (48:E1:5C:6D:F3:A1): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://192.168.1.24:42127/
[8/20/2024, 2:48:00 PM] [Apple TV Enhanced] [W] Garage TV (48:E1:5C:6D:F3:A1): Pairing request timed out, retrying ...
[8/20/2024, 2:48:00 PM] [Apple TV Enhanced] [W] Garage TV (48:E1:5C:6D:F3:A1): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://192.168.1.24:42127/
[8/20/2024, 2:48:01 PM] [Apple TV Enhanced] [W] Garage TV (48:E1:5C:6D:F3:A1): Apple TV Garage TV: Too many attempts. Waiting for 10773 seconds before retrying. The webpage to pair the Apple TV will become available again when the plugin is attempting the next pairing attempt.
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 1,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "updateCheckLevel": "stable",
    "updateCheckTime": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideAbsoluteVolumeControl": false,
            "absoluteVolumeControl": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "name": "HB AppleTVEnhanced-Bridge",
        "username": "0E:92:DC:11:64:9C",
        "port": 44212
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspbian GNU/Linux

### Operating System: Distribution Version

11 Bullseye

### Docker

no

### Docker Image

None

### Docker Image Tag

n/a

### Homebridge Version

v4.56.4

### Homebridge Config UI Version

v4.56.4

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

v1.5.2

### Node Version

v20.11.0 

### NPM Version

10.2.4

### Python Version

3.9.2

### PIP Version

pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)

### HDMI Hops

Direct

### Audio Output

no

### Same Subnet

yes

### Additional Context

see logs above

**Comment by maxileith** [comment] 2024-08-21 06:54
Duplicate of #290

The paring process is also explained in detail in the README

**Closed by maxileith** 2024-08-21 06:54 UTC
Labels: support request, bad request

**Comment by rdeutsch3** [comment] 2024-08-21 12:40
OK, so the current suggestion is to turn off the plug in for greater than the timeout period to get it to reset to a shorter timeout and stand in front of the TV to quickly enter the code?
