### ISSUE TITLE
Pairing Lost Overnight

### ISSUE THREAD

**Issue by greggsymington** [maxileith/homebridge-appletv-enhanced#2] opened 2023-11-01 13:35 UTC
My Apple TV lost pairing or the plugin was trying to add the same Apple TV again. The attempt to re-pair caused the TV to turn on. The only way to get it to stop was repairing.  See the log below.

```

[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Media Type State: unknown
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Device State: idle
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Media Type State: unknown
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Device State: idle
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Media Type State: null
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Device State: null
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Active State: off
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): Turning off
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Media Type State: null
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Device State: null
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Active State: off
[10/31/2023, 11:06:41 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): Turning off
[10/31/2023, 11:27:25 PM] [Apple TV Enhanced] Platform: Adding Apple TV Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED)
[10/31/2023, 11:27:25 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:27:27 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Active State: on
[10/31/2023, 11:27:27 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): Turning on
[10/31/2023, 11:27:27 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Active State: on
[10/31/2023, 11:27:27 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): Turning on
[10/31/2023, 11:27:29 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Active State: on
[10/31/2023, 11:27:29 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Active State: on
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Media Type State: unknown
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Device State: idle
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Media Type State: unknown
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Device State: idle
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Media Type State: unknown
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Device State: idle
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Media Type State: unknown
[10/31/2023, 11:27:36 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CCD2815F30B0): New Device State: idle
[10/31/2023, 11:27:57 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Pairing request timed out, retrying ...
[10/31/2023, 11:27:57 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:28:29 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Pairing request timed out, retrying ...
[10/31/2023, 11:28:30 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:28:59 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote play/pause
[10/31/2023, 11:28:59 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): Turning on
[10/31/2023, 11:29:01 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Media Type State: unknown
[10/31/2023, 11:29:01 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): New Device State: idle
[10/31/2023, 11:29:01 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote back
[10/31/2023, 11:29:02 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Pairing request timed out, retrying ...
[10/31/2023, 11:29:02 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:29:02 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote play/pause
[10/31/2023, 11:29:04 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote back
[10/31/2023, 11:29:05 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote back
[10/31/2023, 11:29:07 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote back
[10/31/2023, 11:29:11 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote back
[10/31/2023, 11:29:14 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote back
[10/31/2023, 11:29:17 PM] [Apple TV Enhanced] Apple TV Master Bedroom (CC:D2:81:5F:30:B0): remote information
[10/31/2023, 11:29:34 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Pairing request timed out, retrying ...
[10/31/2023, 11:29:34 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:30:06 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Pairing request timed out, retrying ...
[10/31/2023, 11:30:06 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:30:38 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Pairing request timed out, retrying ...
[10/31/2023, 11:30:39 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:31:11 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Pairing request timed out, retrying ...
[10/31/2023, 11:31:11 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:31:13 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Apple TV Master Bedroom: Too many attempts. Waiting for 37 seconds before retrying.
[10/31/2023, 11:31:50 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.0.200:42239/
[10/31/2023, 11:31:58 PM] [Apple TV Enhanced] Master Bedroom (3E85370E-C84D-44D3-BEB7-8ACF770B25ED): Got PIN 4862 for Apple TV Master Bedroom.
```

**Comment by maxileith** [comment] 2023-11-01 16:46
Hi @greggsymington,

are you using static IPs for your Apple TVs?

**Comment by maxileith** [comment] 2023-11-01 17:01
Could you please send the output of `/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript scan`?

**Comment by greggsymington** [comment] 2023-11-01 17:01
> Hi @greggsymington,
> 
> are you using a static IP for your Apple TV?

No.

**Comment by greggsymington** [comment] 2023-11-01 17:08
> Could you please send the output of `/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript scan`? If your homebridge storage path is not `/var/lib/homebridge` please adjust the command to your storage path.

`atvscript scan` not at path above. See ls -a below.

```
.   Activate.ps1  activate.csh   atvlog    atvremote  easy_install      mid3cp     mid3v2     mutagen-inspect  normalizer  pip3     pip3.8  python3   tabulate
..  activate      activate.fish  atvproxy  atvscript  easy_install-3.8  mid3iconv  moggsplit  mutagen-pony     pip         pip3.11  python  srptools
```

**Comment by maxileith** [comment] 2023-11-01 17:14
@greggsymington if you are in the directory and want to execute a file, you need to use `./atvscript scan` otherwise only the executables in your PATH env variable will be taken into consideration.

**Comment by greggsymington** [comment] 2023-11-01 17:17
> Which system are you using for Homebridge? OS / Distro

Unraid with the oznu/hombridge Docker container.


> @greggsymington if you are in the directory and want to execute a file, you need to use `./atvscript scan` otherwise only the executables in your PATH env variable will be taken into consideration.

Sorry, had a brainfart and thought you were looking for a log. I've edited the comment above with the output of the scan.

**Comment by maxileith** [comment] 2023-11-01 17:28
Can you send me a Part of your current logs?

Did the repairing happend when your Apple TV got a new IP? Can you maybe renew your Lease on the Apple TV to Test if that reoccurs?

I will try to reproduce the problem later. Of you could provide me a Description Home to reproduce it that wolle be awesome.

**Comment by greggsymington** [comment] 2023-11-01 17:41
> Can you send me a Part of your current logs?
> 
> Did the repairing happend when your Apple TV got a new IP? Can you maybe renew your Lease on the Apple TV to Test if that reoccurs?
> 
> I will try to reproduce the problem later. Of you could provide me a Description Home to reproduce it that wolle be awesome.

I did not think to check if the IP address changed in the moment, I was a bit groggy just trying to get the TV to turn off. I will try the lease renewal this evening when I get home and see if it produces the same result.  

Please see the log attached from when the issue occurred until now.
[HB_LOG.txt](https://github.com/maxileith/homebridge-appletv-enhanced/files/13230098/HB_LOG.txt)

**Comment by greggsymington** [comment] 2023-11-01 21:26
> Did the repairing happend when your Apple TV got a new IP? Can you maybe renew your Lease on the Apple TV to test if that reoccurs?

For full disclosure, I and testing on another Apple TV on the same network.

I am not able to renew lease via Apple TV or eero so I reserved it as a different static and restarted the Apple TV. It did not trigger a re-pairing but did show the following error

`[11/1/2023, 5:14:08 PM] [Apple TV Enhanced] Apple TV Living Room (1C:B3:C9:3A:88:A5): Lost connection. Trying to reconnect ...`

Returning it to the original IP left the plugin in the error state until Homebridge was restarted. Running atvscript scan shows the Apple TV in question with the correct (old) IP.

**Comment by maxileith** [comment] 2023-11-01 22:29
Thanks for analyzing the situation. I have successfully reproduced the bug that you have described here:

> `[11/1/2023, 5:14:08 PM] [Apple TV Enhanced] Apple TV Living Room (1C:B3:C9:3A:88:A5): Lost connection. Trying to reconnect ...`
> 
> Returning it to the original IP left the plugin in the error state until Homebridge was restarted. Running atvscript scan shows the Apple TV in question with the correct (old) IP.

So the problem here is that there is no new object created from the device discovery results that contains the new IP. I simply did not come across this issue until now, since I am using a static IP on my Apple TV because the plugin that I have used before requires that. 

Of course, I do not want this as a requirement for my plugin. Therefore, I have just pushed a fix for that problem (v.0.2.1-beta.9).

**Comment by maxileith** [comment] 2023-11-01 22:39
I cannot reproduce the problem for which you have opened this issue for in the first place (first message with the logs), nor can I understand how this came about.

Above all, it confuses me that the ID of the Apple TV is once the MAC address, once the MAC address without colons and once a UUID in the logs. Actually, the MAC address always serves as the identifier in my plugin. This is very weird since all Log messages of a device are created by the same logger, that should always use the same prefix: Device (AA:BB:CC:DD:EE:FF)

**Comment by greggsymington** [comment] 2023-11-01 23:09
> Above all, it confuses me that the ID of the Apple TV is once the MAC address, once the MAC address without colons and once a UUID in the logs. Actually, the MAC address always serves as the identifier in my plugin. This is very weird since all Log messages of a device are created by the same logger, that should always use the same prefix: Device (AA:BB:CC:DD:EE:FF)

It confuses me even more as the MAC address show is not correct for the device. atvscript and HB log shows it as `(CC:D2:81:5F:30:B0)` but the Apple TV and eero show it as cc:d2:81:66:c5:d7.

**Comment by maxileith** [comment] 2023-11-01 23:35
I have taken a look at the situation on my side as well. atvscript is reporting a different MAC-Address on my side as well. I could imagin that the Apple TV is reporting a different MAC Address for companion and airplay on purpose. So this does not seem to be a specific problem in your setup.

**Comment by maxileith** [comment] 2023-11-01 23:41
However, to come back to the start of the issue, I have noticed that when I execute `atvremote scan` I get the following output:
```
[...]
       Name: Wohnzimmer (2)
   Model/SW: Apple TV 4K (gen 3), tvOS 17.0
    Address: 192.168.0.15
        MAC: A8:51:AB:02:4D:6F
 Deep Sleep: False
Identifiers:
 - SOME_UUID
 - AA:BB:CC:DD:EE:FF
 - AABBCCDDEEFF
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
[...]
```

There we can see, that there are three different identifiers, the MAC-Adress with and without colons and a UUID, like we have seen in your logs from your first message. In comparison, with `atvscript scan` we only get one identifier and it seems to be not clearly defined which identifier is returned by the `atvscript`.

So the problem that you are experiencing has its roots in the pyatv project.

**Comment by maxileith** [comment] 2023-11-02 10:44
I just experienced the bug on my system as well. A new device was created since the discovery reported the UUID as the identifier of my Apple TV. Since this seems to be an edge case and most of the time the MAC-Address is reported, I will filter the discovered devices for MAC-Addresses as identifier. This will do the trick for now.

Could you please install v0.2.1-beta.10 and provide me feedback if the problem reoccurs?

However, for the long term, the error should be fixed in pyatv. I may open a PR over there, if I can manage to get this working.

**Comment by maxileith** [comment] 2023-11-03 21:09
Closing since the repairing prompt did not occur again on my side. Please reopen if it still occurs on your system @greggsymington

**Closed by maxileith** 2023-11-03 21:09 UTC
Labels: bug
