### ISSUE TITLE
Getting constant "SyntaxError: Unexpected non-whitespace character after JSON at position" errors.

### ISSUE THREAD

**Issue by pmoney303** [maxileith/homebridge-appletv-enhanced#407] opened 2024-05-18 22:36 UTC
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

The log contains repeated errors relating to an unexpected non-whitespace character.  The error occurs indefinitely.

### Logs

```console
Verbose logs attached below
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "tv"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "home",
        "play_pause",
        "turn_off",
        "turn_on",
        "volume_down",
        "volume_up"
    ],
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": true,
    "discover": {
        "multicast": true,
        "unicast": [
            "10.0.0.30",
            "10.0.0.229",
            "10.0.0.79",
            "10.0.0.20",
            "10.0.0.156",
            "10.0.0.232"
        ],
        "blacklist": [
            "D0:03:4B:4C:2A:2E"
        ]
    },
    "forceVenvRecreate": false,
    "logLevel": 5,
    "updateCheckLevel": "stable",
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "0E:B5:72:15:33:F2",
        "port": 41049
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspberry Pi OS

### Operating System: Distribution Version

12 (bookworm)

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.2

### Homebridge Config UI Version

4.56.2

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.3.1

### Node Version

20.12.2

### NPM Version

10.5.0

### Python Version

3.11.2

### PIP Version

23.0.1

### HDMI Hops

None

### Audio Output

no

### Same Subnet

yes

### Additional Context

[homebridge-appletv-enhanced.log (4).txt](https://github.com/maxileith/homebridge-appletv-enhanced/files/15367030/homebridge-appletv-enhanced.log.4.txt)

**Comment by pmoney303** [comment] 2024-05-18 22:42
Logs are attached

**Comment by maxileith** [comment] 2024-06-18 22:36
Thanks for providing the verbose logs. These are actually very helpful as I have just analyzed the problem. The issue is part of a dependency I am using in the plugin. I opened a ticket regarding this issue here: https://github.com/sebbo2002/node-pyatv/issues/324

As a workaround you can remove the Apple TVs `10.0.0.229` and `10.0.0.232` from the unicast discovery setting. As they are note reachable by the plugin.

**Comment by maxileith** [comment] 2024-06-25 18:59
Closing since I am sure this has been fixed

**Closed** 2024-06-25 18:59 UTC
Labels: support request
