### ISSUE TITLE
How to trigger the pairing

### ISSUE THREAD

**Issue by goodoldboy** [maxileith/homebridge-appletv-enhanced#354] opened 2024-04-07 00:05 UTC
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hi, is there a way to trigger the pairing process manually? I never catch when it pops up and way too short to open the link etc. And Usually pops up in the middle of the night too. I restart the homebridge again but it does not seem to trigger it. I have 4 apple TV's and managed to sync only one so far. Thx

**Comment by maxileith** [comment] 2024-04-08 15:24
HI @goodoldboy,

please take a look here https://github.com/maxileith/homebridge-appletv-enhanced/issues/290#issuecomment-1967363338. This is a know issue and is up for improvement.

**Comment by maxileith** [comment] 2024-04-08 15:31
@goodoldboy I have opened an enhancement request regarding this topic as this has been mentioned multiple times. This enhancement request also includes a workaround that should work for you as well: here https://github.com/maxileith/homebridge-appletv-enhanced/issues/359#issuecomment-2043064454

duplicate of #359

**Closed by maxileith** 2024-04-08 15:31 UTC
Labels: general question
