### ISSUE TITLE
When navigating back to Home Screen, plugin reports Apple Music as being the active app, not Home

### ISSUE THREAD

**Issue by beslergr** [maxileith/homebridge-appletv-enhanced#230] opened 2024-02-04 17:50 UTC
### Analysis

When exiting out of one app, and going back to the Apple TV Home Screen, plugin shows Apple Music as the active app, instead of Home. Seems to only occur when Apple Music has been previously opened.

### Expected Behavior

Should show Home, not Apple Music.

### Steps To Reproduce

1. Ensure Apple Music is one of the apps in the app picker, and that it has been open previously.
2. Open up another app like Netflix.
3. Go back to the Apple TV Home Screen.
4. Check plugin in the Home app, and it should say Apple Music, despite that app not being active.

### Logs

```console
[04/02/2024, 12:21:50] [Apple TV Enhanced] Initializing AppleTVEnhanced platform...
[04/02/2024, 12:21:50] [Apple TV Enhanced] Initializing child bridge 0E:BC:CE:C7:99:79
[04/02/2024, 12:21:50] Loading 5 accessories...
[04/02/2024, 12:21:54] [Apple TV Enhanced] Launched child bridge with PID 31724
[04/02/2024, 12:21:55] [Apple TV Enhanced] Loaded homebridge-appletv-enhanced v1.2.1 child bridge successfully
[04/02/2024, 12:21:55] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced
[04/02/2024, 12:21:55] [Apple TV Enhanced] [I] Python check: Starting python check.
[04/02/2024, 12:21:55] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[04/02/2024, 12:21:55] [Apple TV Enhanced] [I] Python check: Python 3.9.2 is installed and supported by the plugin.
[04/02/2024, 12:21:55] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[04/02/2024, 12:21:55] Homebridge v1.7.0 (HAP v0.11.1) (Security System) is running on port 50309.
[04/02/2024, 12:21:55] Homebridge v1.7.0 (HAP v0.11.1) (Arrive Home) is running on port 35477.
[04/02/2024, 12:21:55] [Apple TV Enhanced] [I] Python check: Venv is using current system python version (3.9.2).
[04/02/2024, 12:21:55] Homebridge v1.7.0 (HAP v0.11.1) (Garage Dummy) is running on port 51506.
[04/02/2024, 12:21:55] Registering accessory 'homebridge-dummy.DummySwitch'
[04/02/2024, 12:21:58] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.0
[04/02/2024, 12:21:58] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[04/02/2024, 12:21:58] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[04/02/2024, 12:22:00] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[04/02/2024, 12:22:00] [Apple TV Enhanced] [I] Python check: Finished
[04/02/2024, 12:22:00] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[04/02/2024, 12:22:06] [Apple TV Enhanced] [I] Platform: Adding Apple TV Living Room (2) ()
[04/02/2024, 12:22:06] [Apple TV Enhanced] [I] Living Room (2) (): verifying credentials ...
[04/02/2024, 12:22:08] [Apple TV Enhanced] [I] Living Room (2) (): Credentials are still valid. Continuing ...
[04/02/2024, 12:22:08] [Apple TV Enhanced] [I] Living Room (2) (): Exposing Apple TV as accessory of type set-top box.
[04/02/2024, 12:22:10] [Apple TV Enhanced] [I] Apple TV (): Finished initializing
[04/02/2024, 12:22:10] Apple TV Living Room (2) 3618 is running on port 36725.
[04/02/2024, 12:22:10] Please add [Apple TV Living Room (2) 3618] manually in Home app. Setup Code: 155-37-516
[04/02/2024, 12:22:11] [Apple TV Enhanced] [I] Apple TV (): New Active State: on
[04/02/2024, 12:22:11] [Apple TV Enhanced] [I] Apple TV (): New Media Type State: unknown
[04/02/2024, 12:22:11] [Apple TV Enhanced] [I] Apple TV (): Current App: com.google.ios.youtubeunplugged
[04/02/2024, 12:22:14] [Apple TV Enhanced] [I] Apple TV (): New Device State: playing
(node:31720) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[04/02/2024, 12:35:49] [Apple TV Enhanced] [I] Apple TV (): New Device State: paused
[04/02/2024, 12:36:15] [Apple TV Enhanced] [I] Apple TV (): Rocket Remote: launch_app=com.netflix.Netflix
[04/02/2024, 12:36:21] [Apple TV Enhanced] [I] Apple TV (): Rocket Remote: home
[04/02/2024, 12:36:27] [Apple TV Enhanced] [I] Apple TV (): Rocket Remote: launch_app=com.netflix.Netflix
[04/02/2024, 12:36:46] [Apple TV Enhanced] [I] Apple TV (): Current App: com.netflix.Netflix
[04/02/2024, 12:36:49] [Apple TV Enhanced] [I] Apple TV (): New Device State: playing
[04/02/2024, 12:37:00] [Apple TV Enhanced] [I] Apple TV (): Current App: com.apple.TVMusic
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStates": [
        "paused",
        "playing"
    ],
    "deviceStateDelay": 3,
    "avadaKedavraAppAmount": 25,
    "disableVolumeControlRemote": false,
    "setTopBox": true,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "platform": "AppleTVEnhanced",
    "_bridge": {
        "username": "0E:BC:CE:C7:99:79",
        "port": 31494
    }
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Docker: false
  - Image Version: 
- Homebridge: v1.7.0
- Homebridge Config UI: v4.55.1
- Storage Path: /var/lib/homebridge
- Apple TV Enhanced: v1.2.1
- Node: v20.11.0
- npm: 10.2.4
- Python: 3.9.2
- pip: 20.3.4
- HDMI hops: AppleTV direct connected to television. Sonos Beam as eARC sound bar, connected to television. PS5 connected to television.
- HomePod as default speaker: false

**Comment by maxileith** [comment] 2024-02-04 21:08
> Should show Home, not Apple Music.

The problem is, that the Apple TV does not report when the user navigates to the home screen. Instead it reports Apple Music as the active app. I have the same problem on my side as well. There is nothing I can really do about that. This has to be fixed on the Apple TV itself.

**Closed** 2024-02-05 07:51 UTC
Labels: bug
