### ISSUE TITLE
Deleted pairing in Apple TV now can't repair.

### ISSUE THREAD

**Issue by Glec6** [maxileith/homebridge-appletv-enhanced#12] opened 2023-11-05 19:02 UTC
How to repair or unpair to repair device. Tried uninstalling on homebridge plugin, still "detects" then has error. Tried resetting the Apple TV, still same issue. Is there a way to unpair to repair?

**Comment by maxileith** [comment] 2023-11-05 21:54
To reset the plugin completly, you need to delete the plugin storage folder at `/var/lib/homebridge/appletv-enhanced` assuming your homebridge storage path is `/var/lib/homebridge`.

**Comment by maxileith** [comment] 2023-11-05 22:11
However, this is definetly a good issue that you are raising here. The plugin should definetly detect when the credentials are not valid anylonger and then initiate a pairing request.

**Comment by maxileith** [comment] 2023-11-05 23:42
@Glec6 fixed in v0.3.1-beta.1

**Closed** 2023-11-05 23:46 UTC
Labels: enhancement, question

**Comment by johnlietzke** [comment] 2023-11-16 20:22
On a Pi 4 running Raspberry Pi OS and cannot find the `~/.pyatv.conf`.  Have one ATV paired 3 not promoting for the pin and one throwing an error. 

Any idea where ~/.pyatv.conf is located?

**Comment by maxileith** [comment] 2023-12-25 09:47
Hi @johnlietzke ,

if the issue is still present, please open a bug report.
